[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
orca-whirlpools-core = "0.1"   
orca-whirlpools-client = "0.1"  
mpl-token-metadata = "1.9.9"